### ISSUE TITLE
Support Docker Compose 1.6

### ISSUE THREAD

**Issue by Perlence** [brgmnn/fish-docker-compose#1]
Docker Compose 1.6 introduced new file format and added a new command `docker-compose events`.[[1]](https://blog.docker.com/2016/02/compose-1-6/) That unfortunately means that service name suggestion won't work properly with new docker-compose.yml.

**Comment by brgmnn** [comment]
Sure, I'll look in to it :)

**Comment by Perlence** [comment]
Thank you very much :smile:
