### ISSUE TITLE
Adding optional argument completions

### ISSUE THREAD

**Issue by lwolfsonkin** [brgmnn/fish-docker-compose#11]
The main docker-compose repo has [a minimal set of completions](https://github.com/docker/compose/blob/master/contrib/completion/fish/docker-compose.fish) that only contains some optional `--` style arguments on the main `docker-compose` command. Those don't seem to be in this repo. Could those be added?

**Comment by brgmnn** [comment]
Good spot, I'll add the missing completions. Thanks!
