### ISSUE TITLE
Consider using docker-compose introspection

### ISSUE THREAD

**Issue by Fuco1** [brgmnn/fish-docker-compose#14]
### Describe the problem

They way the parsing for services/version is done currently seems a bit problematic.  Docker compose has built-in introspection via `docker-compose config [--services]` so you can use the output of that to get the version or list of services.

This should also make it possible to get it to work with multiple docker compose files (via `-f` flag) as the output of that command is the "merged" list.

My fish-fu is quite weak but if you have some questions on docker I'm happy to answer those.

**Comment by brgmnn** [comment]
This is a great idea, thanks for bringing it to my attention. I'll have a look at it.

**Comment by Fuco1** [comment]
I've found a little bit more complete project and created a PR with this very feature, it wasn't as time consuming as I thought: https://github.com/fisherman/docker-completion/pull/5

The cool thing there is that the whole thing is generated automatically from the output of `docker --help` or `docker-compose --help` so updating is quite trivial (just re-run the generator script).

Feel free to have a look or take the code :)
