### ISSUE TITLE
Problems on Debian

### ISSUE THREAD

**Issue by cocolabombe0** [brgmnn/fish-docker-compose#2]
Hello, I touch you because I want to know if it is possible to adapt on debian. I want to use for fish-docker made without success.
Thank you.
Have a good day

**Comment by brgmnn** [comment]
Hey, so I tried out setting up docker, docker-compose and the fish completions in a blank Debian virtual machine and everything seems to work correctly. I was running Debian Jessie (8.3) with fish version 2.2.

Could you give me some more details about what wasn't working for you? And also some more details about your setup such as what version of Debian, Fish, Docker and Docker Compose?

**Comment by cocolabombe0** [comment]
Hey, 
Debian 8.3 / Fish Version 2.2.0 / docker 1.5-1 / Docker compose ?
I install with fundle:
`mkdir -p ~/.config/fish/functions
wget https://raw.githubusercontent.com/tuvistavie/fundle/master/functions/fundle.fish -O ~/.config/fish/functions/fundle.fish`
add `#vim ~/.config/fish/config.fish :`
`#Docker-compose
fundle plugin 'brgmnn/fish-docker-compose'
fundle init
`

run the command:
`fundle install`
[Installing brgmnn/fish-docker-compose
tuvistavie/fish-completion-helpers not installed. You may need to run 'fundle install'
See the docs for more info. https://github.com/tuvistavie/fundle
brgmnn/fish-docker-compose installed in /root/.config/fish/fundle/brgmnn/fish-docker-compose
Installing tuvistavie/fish-completion-helpers
]

And I still do not have the docker-made available.
what I forgot or wrong.
Sincerely Nicolas

**Comment by brgmnn** [comment]
Hmm are you referring to some other docker commands? I'm not familiar with `docker-made`. Just to note though this repo only provides completions for the `docker-compose` command, **not** docker. For docker completions I use https://github.com/barnybug/docker-fish-completion.

The installation command seems to have worked correctly though. Do you have any completions on `docker-compose`? For example you should see something like this if you double tap tab after `docker-compose` in fish:
<img width="402" alt="screen shot 2016-03-27 at 2 33 53 pm" src="https://cloud.githubusercontent.com/assets/1955273/14067956/0c8ff640-f429-11e5-99d7-270b4ed29105.png">

If you see that then the completions from this repo are working correctly! But yes I'm not sure what docker made is?

**Comment by cocolabombe0** [comment]
No, docker-compose remains red
docker-made (error french -> english).
I tried to install your completions but I still have a problem.
http://www.hostingpics.net/viewer.php?id=394663Capture.png

**Comment by brgmnn** [comment]
Ahh, do you have docker compose installed? If `docker-compose` is red in fish that means it can't find the binary. You have to install it as well as docker, here is how you would do so: https://docs.docker.com/compose/install/

And I'm not sure what I should see in that picture, it's some highlighted files in a Windows C drive. Am I missing something?

**Comment by cocolabombe0** [comment]
Error of file : http://img15.hostingpics.net/pics/394663Capture.png
http://img15.hostingpics.net/pics/848088Capture2.png

docker-compose is been installed. (Method Alias in ~/.profile

**Comment by brgmnn** [comment]
Hmm that's weird. What's the output of `which docker-compose`? I have this:

<img width="222" alt="screen shot 2016-03-27 at 4 04 31 pm" src="https://cloud.githubusercontent.com/assets/1955273/14068362/a2aff9b6-f435-11e5-828d-559df7f5ade6.png">

If docker compose is installed correctly you should have something similar. If you have an alias for docker compose, the alias should point to the binary.

**Comment by cocolabombe0** [comment]
The command is executed without data feedback.

**Comment by brgmnn** [comment]
Hmm that means it can't find docker-compose. You posted a screenshot of it working in another shell though, is docker-compose in your PATH for fish?

**Comment by cocolabombe0** [comment]
The /bin/bash  was to show that I have made the docker-compose.
I had no docker-compose.fish file in the folder completion. I just add it manually.
What should I do to check other.

The auto mode is copying the file /root/.config/fish/fundle/brgmnn/fish-docker-compose

**Comment by brgmnn** [comment]
Where ever you installed docker-compose, you need to make sure you add it to your PATH for fish. That seems to be the problem as fish can't find docker compose. See this part of the fish documentation on adding a directory to your PATH: http://fishshell.com/docs/current/tutorial.html#tut_path

But basically you need to run something like `set -U fish_user_paths /path/to/install/folder $fish_user_paths` where `/path/to/install/folder` is where you installed docker-compose.

You shouldn't see any files being added by fundle into the completions folder, it sources them from where it clones the plugin git repo, that's normal. The screenshots you posted it looked like it was installing just fine.

**Comment by cocolabombe0** [comment]
set -U fish_user_paths /root/.config/fish/fundle/brgmnn/fish-docker-compose $fish_user_paths

basically, I must add that in my config.fish file?
This is the link of docker-compose.fish

edit: On a clean test server, I installed docker-compose by pip and fish without adding works directly with fish.
After, I just see that the alias was not working well with fish (I think)

**Comment by brgmnn** [comment]
I think you only need to set the fish user path once (-U makes it permanent I believe) but yes it sounds like docker compose just wasn't in your bin path :)

I will mark this as won't fix and close it.
