### ISSUE TITLE
Support docker-compose v1.7.0

### ISSUE THREAD

**Issue by whitelynx** [brgmnn/fish-docker-compose#4]
[Version 1.7.0](https://github.com/docker/compose/releases/tag/1.7.0) added several new flags and commands:
- the `-f` flag for `docker-compose logs`
- the `--remove-orphans` flag for `docker-compose up` and `docker-compose down`
- the `--all` flag for `docker-compose rm`
- the same TLS configuration flags used by the docker client (`--tls`, `--tlscert`, `--tlskey`, etc.)
- the `--workdir` flag for `docker-compose run`
- the `--follow`, `--timestamp`, and `--tail` flags for `docker-compose logs`
- the `--build` flag for `docker-compose up`
- the `docker-compose exec` command

**Comment by brgmnn** [comment]
Thanks for notifying me, I'll get on it!

**Comment by brgmnn** [comment]
I think I covered everything in a82822c820f0a7e8a6e8cbaafec37572de20fa22.
