### ISSUE TITLE
Autocompletion doesn't work

### ISSUE THREAD

**Issue by schickling** [brgmnn/fish-docker-compose#5]
When I'm hitting tab I'm getting the following result:

![](https://i.gyazo.com/df0d147f8b2c9aa999a45c473489517a.gif)

**Comment by brgmnn** [comment]
Hmm interesting, what version of docker compose are you using and are you using version 2 of the `docker-compose.yml` file format?

**Comment by brgmnn** [comment]
I checked locally and found the issue. I've pushed a fix so update your plugins with fundle/fisherman. Thanks for alerting me of this! 👍

**Comment by schickling** [comment]
Great job for fixing it so fast 👍
