### ISSUE TITLE
Autocompletion error

### ISSUE THREAD

**Issue by AlterEgo7** [brgmnn/fish-docker-compose#9]
### Describe the problem

Autocomplete on service name produces the following error:

```
~/.config/fish/completions/docker-compose.fish (line 5): switch: Expected exactly one argument, got 2

    switch $file_version
           ^
in function '__fish_docker_compose_all_services'
	called on standard input

in command substitution
	called on standard input
```
### Software versions

Fish Shell version: 2.6.0
Docker Compose version: 1.16.1
Compose file version: 2.1

**Comment by brgmnn** [comment]
Thanks for filing a bug, I'll take a look at it :)

**Comment by AlterEgo7** [comment]
Nice. Thanks for the quick resolution.
